version: '3.2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules  
    ports:
      - "5000:5000"
    command: npm run start
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/test
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    restart: always
   # ports:
    #  - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    restart: always
   # ports:
   #   - "6379:6379"

volumes:
  mongo-data:
